### ISSUE TITLE
replace Dark Sky with another weather API provider

### ISSUE THREAD

**Issue by mrjones-plip** [mrjones-plip/YANPIWS#69]
Now that Dark Sky [isn't taking new sign ups](https://blog.darksky.net/dark-sky-has-a-new-home/) (and will be closing the API entirely in ~18 mo), we should work with another API provider. Some candidates are:
*  [weather.gov](https://www.weather.gov/documentation/services-web-api) 
* [Sunrise Sunset (no weather)](https://sunrise-sunset.org/api)
* [Time and Date (not free?)](https://services.timeanddate.com/api)
* [Openweathermap](https://home.openweathermap.org/) 
* [Worldweatheronline](http://www.worldweatheronline.com/)
* [Open-Meteo](https://open-meteo.com/en/docs)

we should pick one that works and go with it!  Requirements are:

* get forecast with 5-7 days 
* forecast should have 
  * hi temp
  * low temp
  * wind speed
  * 1 - 2 word description to match to icon
  * humidity
* get detailed forecast for current day
* get today's sunset sunrise
* moar? we should look at darksky

**Comment by open-meteo** [comment]
Creator of open-meteo here

I would be happy to support you in the implementation. Let me know if you need additional weather variables or having issues with the implementation. Just yesterday I finished the implementation of daily weather variables with sunrise and sunset time.

Best, Jeff

**Comment by mrjones-plip** [comment]
@open-meteo -  So nice of you stop by our lil' project and offer to help out - thank you! 

I'll be sure to keep you posted here if we have any questions (and am happy to open formal feature requests in [the correct location](https://github.com/open-meteo/open-meteo) if need be!)

**Comment by mrjones-plip** [comment]
I see that pirateweather.net offers:

> An unprocessed weather forecast API, built to be fully Dark Sky compatible.

so it should be a drop in replacement.

**Comment by mrjones-plip** [comment]
@open-meteo  - Does open-meteo.com have an API that returns the same response format as Dark Sky and [Pirate Weather](https://pirateweather.net)?  Ideally it'd match the [URL pattern](https://github.com/mrjones-plip/YANPIWS/pull/99#issue-1653173299) as well, but I can likely work around that.

**Comment by mrjones-plip** [comment]
with #99 PR and 0.10.0 [release](https://github.com/mrjones-plip/YANPIWS/releases/tag/0.10.0), this issue is fixed
