### ISSUE TITLE
Changing font sizes in config.csv are not tied to label

### ISSUE THREAD

**Issue by mdes0701791** [mrjones-plip/YANPIWS#98]
Changing 'font_temp_label' does nothing. The actual font size of the Temp labels are tied to the 'font_time_date_wind' instead.

```csv
# CSS font sizes
font_time_date_wind,50
font_temp,55
font_temp_label,13
```

**Comment by mrjones-plip** [comment]
Which version are you on? You can tell by clicking on the "YANPIWS" at the top of the screen.  Variable font sizes were[ added in 0.9.9](https://github.com/mrjones-plip/YANPIWS#version-history).

As well, can you paste in your `config.csv` verbatim to look at it? Please be sure to obscure your `api_password`, `api_password`, `darksky`, `lat` and `long` if you so desire - they may contain sensitive info. 

Here's mine:

```csv
lat,1.999091
lon,-1.104737
darksky,e-SNIP-83
labels_74,Out
labels_231,In
labels_55,Up
labels_71,E
labels_75,V
animate,false
temp_count,3
dataPath,/home/pi/YANPIWS/data/

# CSS font sizes
font_time_date_wind,35
font_temp,50
font_temp_label,25

api_password,boxcar-spinning-problem-rockslide-scored
servers_0_url,http://127.0.0.1
servers_0_password,boxcar-spinning-problem-rockslide-scored
```

And then here's a lil video of my set up working:

https://user-images.githubusercontent.com/8253488/183259446-0959f58c-95b9-4849-a4e0-3d72411bd744.mp4

**Comment by mdes0701791** [comment]
Running version 0.9.10

Yep 

Config.csv truncated to omit sensitive data
```
# should we show animated icons for forecast? should be "true" or "false"
animate,true

# label ID map to human name. Format is "labels_" + ID + "," + NAME
labels_12828,Patio
labels_12281,Attic
labels_2405,Garage
labels_14593,Backyard

# How many temperatures to show on the screen (tested with 1, 2 or 3 - watch out if you do more!)
temp_count,4

# CSS font sizes
font_time_date_wind,25
font_temp,40
font_temp_label,5
```
Changing *font_temp_label* value still does nothing on Chrome, Opera, Firefox.

**Comment by mrjones-plip** [comment]
@mdes0701791 - We worked through a clean install for you the other day - does this issue still persist in that new install?

**Comment by zenw01f** [comment]
So far so good! 
Only issue is when using dynamic icons my Opera browser will choke and stop displaying the icons after a period of time - maybe a day or two. Works find in Safari and Chrome

**Comment by mrjones-plip** [comment]
> So far so good!

Great!  I'll close this issue then  - thanks for confirming the font issue is fixed.

> Only issue is when using dynamic icons my Opera browser will choke and stop displaying the icons after a period of time - maybe a day or two. Works find in Safari and Chrome

oh - bummer! If you'd like track this, please open a new issue with steps to reproduce.
